### PR TITLE
Simplify script. Fix incorrect error number calculation e.

### PR DESCRIPTION
**Pull request by amiller**

### CODE REVIEW

**Comment by amiller** [comment]
Hey, there was a bug in estimating the number of errors to decode. Also, right now it determines the number of errors to correct based on the number of non-None values, so to make it run the ordinary case, need to only have 2t+1 non-None values. I also bumped the number to try up to k=1000 or so. Now this is a better starting point for trying to optimize

**Comment by amiller** [comment]
So the fix I suggested here isn't quite right:
```
        assert(t + 1 + c <= n)
        e = (n - c - t - 1) // 2  # number of errors to correct
```
or 
```
        assert(2*t + 1 + c <= n)
        e = (n - c - 2 * t - 1) // 2  # number of errors to correct
```
I think the version in this commit is correct (this also requires some of the test cases to change a bit)
https://github.com/initc3/HoneyBadgerMPC/commit/e39faece457af784f5570d4cc72b618a8e01e274

**Comment by changxu2** [comment]
I found another way to fix this issue as 
if (n - c) == 2*t + 1 :
            e = 0
        else:
            e = (n - c - t - 1) // 2
This will fix not cause other changes to our code base while also maximize the total error that can be corrected in one run of decoding, if there are any.

**Comment by amiller** [comment]
I don't like having a special case rather than just a single expression.... it makes me suspect the expression is wrong

**Pull request merged**
